### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by aamorozov** [aamorozov/JavaProject#1]
- [x] Fix error with transforming object into web element for the images w/ links;
- [x] Merge with JMeter by adding jUnit request to the Thread Group and specifying jUnit4 tests;
- [x] Add a few different templates for the forms mostly used internally on the web applications;
- [x] Add a method to verify that all images presenting on the page are actually loaded and not 404ing in the server response; 
- [x] Execute a load test using existing test suit;
